In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[1 2 3 4 5 6 7 8]
(8,)
8
1
int64


In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(b)
print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)
18
2
int64


In [8]:
c = np.array([10,20,30,40,50,60,70,80, 90])
print(c)
print(c[0])
print(c[1:2])
print(c[::2])
print(c[1::2])
print(c[::-1])
print(c[::-2])

[10 20 30 40 50 60 70 80 90]
10
[20]
[10 30 50 70 90]
[20 40 60 80]
[90 80 70 60 50 40 30 20 10]
[90 70 50 30 10]


In [ ]:
str1 = "Hello World"
print(str1)

1. Create array of n element
2. Write a statement to print the first element
3. Write a statement to print the element at 3
4. Write a statement to print the ast element using positive indexing
5. Write a statement to print the last element using negative indexing
6. What will be the output of a[4]
7. Write a statement to print first 3 element
8. Write a statement to print element from 2 to 5(not including 5)
9. Write a statement to print element from 3 to end
10. Write a statement to print all element except the 1st one
11. What is the output of a[:4]
12. Write a statement to print every 2nd element
13. Write a statement to print every 3rd element
14. Write a statement to print element from index 1 to 5 with step 2
15. Write a statement to reverse the array
16. Write a statement to print every 2nd element in reverse order
17. Write a statement to print elements which are greater than 30
18. Write a statement to print even elements
19. Write a statement to print element divisible by 3


In [43]:
# 1. Create array of n element

arr = np.array([10,20,30,40,50,60,70,80, 99, 100])

In [10]:

# 2. Write a statement to print the first element

print(arr[0])

10


In [11]:
# 3. Write a statement to print the element at index 3

print(arr[3])

40


In [50]:
# 4. Write a statement to print the ast element using positive indexing

print(arr[arr.size - 1])

[100  99  80  70  60  50  40  30  20  10]


In [13]:
# 5. Write a statement to print the last element using negative indexing

print(arr[-1])

100


In [14]:
# 6. What will be the output of arr[4]

print(arr[4])

50


In [16]:
# 7. Write a statement to print first 3 element

print(arr[:3])

[10 20 30]


In [17]:
# 8. Write a statement to print element from index 2 to 5(not including 5)

print(arr[2:5])

[30 40 50]


In [18]:
# 9. Write a statement to print element from index 3 to end

print(arr[3:])

[ 40  50  60  70  80  90 100]


In [19]:
# 10. Write a statement to print all element except the 1st one

print(arr[1:])

[ 20  30  40  50  60  70  80  90 100]


In [20]:
# 11. What is the output of arr[:4]

print(arr[:4])

[10 20 30 40]


In [21]:
# 12. Write a statement to print every 2nd element

print(arr[::2])

[10 30 50 70 90]


In [22]:
# 13. Write a statement to print every 3rd element

print(arr[::3])

[ 10  40  70 100]


In [23]:
# 14. Write a statement to print element from index 1 to 5 with step 2

print(arr[1:5:2])

[20 40]


In [24]:
# 15. Write a statement to reverse the array

print(arr[::-1])

[100  90  80  70  60  50  40  30  20  10]


In [25]:
# 16. Write a statement to print every 2nd element in reverse order

print(arr[::-2])

[100  80  60  40  20]


In [41]:
# 17. Write a statement to print elements which are greater than 30

print(arr[arr >= 30])

[ 30  40  50  60  70  80  90 100]


In [49]:
# 18. Write a statement to print even elements

print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[ 10  20  30  40  50  60  70  80 100]
[99]


In [51]:
# 19. Write a statement to print element divisible by 3

print(arr[arr % 3 == 0])

[30 60 99]
